"""
YouTube Publisher Module
Handles uploading videos to YouTube using OAuth2 and the Data API v3.
"""
import os
import json
import logging
from pathlib import Path
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow

from ..config import ROOT
from ..database import get_channel, log_pipeline_step, update_video

logger = logging.getLogger("youtube-auto-pro.publisher")

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]


def get_authenticated_service(channel_id: str):
    """Retrieve an authenticated YouTube service instance from token file."""
    channel = get_channel(channel_id)
    if not channel:
        raise ValueError(f"Channel {channel_id} not found in DB.")

    token_file = channel.get("oauth_token_file")
    client_file = channel.get("oauth_client_file")

    if not token_file or not client_file:
        raise ValueError(f"Missing OAuth config files for channel {channel_id}. Please run local auth first.")

    token_path = ROOT / token_file
    client_path = ROOT / client_file

    creds = None
    if token_path.exists():
        try:
            creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)
        except Exception as e:
            logger.warning(f"Could not load token file for {channel_id}: {e}")

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            logger.info(f"Refreshing Google OAuth token for {channel_id}...")
            creds.refresh(Request())
            # Save refreshed token
            with open(token_path, "w") as token:
                token.write(creds.to_json())
        else:
            if not client_path.exists():
                raise FileNotFoundError(f"OAuth client secrets {client_path} not found.")
            raise PermissionError(
                f"Token for {channel_id} is completely invalid or missing. "
                "You must authenticate this channel manually first using the desktop flow."
            )

    return build("youtube", "v3", credentials=creds)


def upload_video_to_youtube(video_data: dict, channel_db_id: int):
    """
    Perform a resumable upload of a video to YouTube.
    Runs synchronously. Should be called by the APScheduler thread.
    """
    channel_slug = video_data.get("channel_slug") # This requires joined select, make sure query provides it
    if not channel_slug:
        # Fallback to query
        channel = get_channel_by_id(channel_db_id)
        channel_slug = channel["channel_id"]

    video_path = video_data.get("video_path")
    thumbnail_path = video_data.get("thumbnail_path")
    title = video_data.get("title", "Untitled Auto-Video")
    
    # We may want to read description/tags from metadata if available.
    meta = json.loads(video_data.get("metadata_json", "{}"))
    description = meta.get("description", "Generated by YouTube Automation Pro.")
    tags = meta.get("tags", [])
    if isinstance(tags, str):
        tags = [t.strip() for t in tags.split(",") if t.strip()]

    channel_info = get_channel(channel_slug)
    category_id = channel_info.get("category_id", "22")
    privacy = channel_info.get("privacy_status", "private") # Safest default

    logger.info(f"Starting YouTube upload for {title} ({video_path})")

    try:
        youtube = get_authenticated_service(channel_slug)
        
        body = {
            "snippet": {
                "title": title[:100],
                "description": description[:5000],
                "tags": tags[:500],
                "categoryId": category_id
            },
            "status": {
                "privacyStatus": privacy,
                "selfDeclaredMadeForKids": False
            }
        }

        media = MediaFileUpload(video_path, mimetype="video/mp4", resumable=True)

        insert_request = youtube.videos().insert(
            part=",".join(body.keys()),
            body=body,
            media_body=media
        )

        response = None
        while response is None:
            status, response = insert_request.next_chunk()
            if status:
                logger.info(f"Uploading {channel_slug} video: {int(status.progress() * 100)}%")

        video_id = response.get("id")
        video_url = f"https://www.youtube.com/watch?v={video_id}"
        logger.info(f"Upload complete! Video ID: {video_id}")

        # Upload Thumbnail if any
        if thumbnail_path and os.path.exists(thumbnail_path):
            try:
                youtube.thumbnails().set(
                    videoId=video_id,
                    media_body=MediaFileUpload(thumbnail_path)
                ).execute()
                logger.info(f"Thumbnail uploaded for {video_id}")
            except Exception as e:
                logger.error(f"Failed to set thumbnail: {e}")

        # Update DB
        from datetime import datetime
        update_video(video_data["id"], {
            "youtube_video_id": video_id,
            "youtube_url": video_url,
            "status": "published",
            "published_at": datetime.now().isoformat()
        })
        log_pipeline_step(channel_db_id, video_data["id"], "publish", "ok", f"Published to {video_url}")

        return True

    except Exception as e:
        logger.error(f"YouTube upload failed: {e}")
        update_video(video_data["id"], {
            "status": "error",
            "error_message": f"Upload failed: {str(e)}"
        })
        log_pipeline_step(channel_db_id, video_data["id"], "publish", "error", str(e))
        return False

def get_channel_by_id(db_id: int):
    # Temp helper
    from ..database import get_channel_by_db_id
    return get_channel_by_db_id(db_id)
