import { useState, useEffect } from 'react';
import { fetchIncomeTracking } from '../api';

export default function Income() {
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchIncomeTracking()
      .then(data => {
        setRecords(data.records || []);
        setLoading(false);
      })
      .catch(err => {
        setError(err.message);
        setLoading(false);
      });
  }, []);

  const totalMonthly = records.reduce((sum, r) => sum + (Number(r.estimated_monthly) || 0), 0);

  if (loading) return <div className="page-loader"><div className="spinner"></div></div>;
  if (error) return <div className="error-card">Error: {error}</div>;

  return (
    <div className="page-container fade-in">
      <div className="page-header">
        <div>
          <h1 className="text-3xl font-bold bg-gradient-to-r from-green-400 to-emerald-500 bg-clip-text text-transparent">
            Monetization & Income
          </h1>
          <p className="text-gray-400 mt-2">Track the financial performance compiled by the team.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="glass-card stat-card">
          <h3 className="text-gray-400 mb-1">Projected Total MRR</h3>
          <p className="text-4xl font-black text-green-400">${totalMonthly.toFixed(2)}</p>
          <div className="mt-2 text-xs text-green-500 bg-green-500/10 px-2 py-1 rounded inline-block border border-green-500/20">
            ↑ Trending Up
          </div>
        </div>
        <div className="glass-card stat-card">
          <h3 className="text-gray-400 mb-1">Active Income Streams</h3>
          <p className="text-4xl font-black text-white">{records.length}</p>
          <div className="mt-2 text-xs text-blue-400 bg-blue-500/10 px-2 py-1 rounded inline-block border border-blue-500/20">
            Diversified
          </div>
        </div>
        <div className="glass-card stat-card">
          <h3 className="text-gray-400 mb-1">Highest Earner</h3>
          <p className="text-2xl font-bold text-white truncate text-ellipsis">
            {records.length > 0 ? [...records].sort((a,b)=>b.estimated_monthly-a.estimated_monthly)[0].source : "N/A"}
          </p>
          <div className="mt-2 text-xs text-purple-400 bg-purple-500/10 px-2 py-1 rounded inline-block border border-purple-500/20">
            Top Performing
          </div>
        </div>
      </div>

      <div className="glass-card p-6">
        <h2 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
          <span className="text-green-400">●</span> Stream Breakdown
        </h2>
        
        {records.length === 0 ? (
          <div className="text-center py-12 border border-dashed border-white/10 rounded-xl">
            <span className="text-4xl mb-3 block opacity-50">💸</span>
            <p className="text-gray-400">No income records generated by agents yet.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-white/10 text-gray-400 uppercase text-xs tracking-wider">
                  <th className="p-4 font-medium">Source</th>
                  <th className="p-4 font-medium">Channel</th>
                  <th className="p-4 font-medium">Agent</th>
                  <th className="p-4 font-medium">Confidence</th>
                  <th className="p-4 font-medium text-right">Est. Monthly</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {records.map((r, i) => (
                  <tr key={i} className="hover:bg-white/5 transition-colors group">
                    <td className="p-4">
                      <div className="font-semibold text-white">{r.source}</div>
                    </td>
                    <td className="p-4 0">
                      <span className="badge badge-outline">{r.channel}</span>
                    </td>
                    <td className="p-4 text-gray-400">
                      <span className="text-xs font-mono bg-black/40 px-2 py-1 rounded text-cyan-400 border border-cyan-500/20">
                        {r.agent}
                      </span>
                    </td>
                    <td className="p-4">
                      <span className={`text-xs px-2 py-1 rounded border ${
                        r.confidence === 'high' ? 'bg-green-500/10 text-green-400 border-green-500/20' :
                        r.confidence === 'medium' ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20' :
                        'bg-red-500/10 text-red-400 border-red-500/20'
                     }`}>
                        {r.confidence}
                      </span>
                    </td>
                    <td className="p-4 text-right font-mono text-green-400 font-bold">
                      ${Number(r.estimated_monthly).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
